In [27]:
import numpy as np

values = np.arange(50, 101)

values

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [28]:
neg = np.ones(10)
neg

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
teg = np.zeros(10)
teg

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
zurgaa = np.full(10, 6)
zurgaa

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [31]:
values = np.arange(20, 32).reshape(3, 4)
values

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [10]:
diagonal_neg= np.eye(3)
diagonal_neg

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
diagonal_toonuud = np.diag(np.arange(1, 6))
diagonal_toonuud 

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [33]:
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
total_sum = np.sum(array_2d)

column_sums = np.sum(array_2d, axis=0)

row_sums = np.sum(array_2d, axis=1)

"2 хэмжээст массив:", array_2d

('2 хэмжээст массив:',
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [19]:
"Нийт элементүүдийн нийлбэр:", total_sum

('Нийт элементүүдийн нийлбэр:', 78)

In [16]:
"Багануудын нийлбэр:", column_sums

('Багануудын нийлбэр:', array([15, 18, 21, 24]))

In [17]:
"Мөрнүүдийн нийлбэр:", row_sums

('Мөрнүүдийн нийлбэр:', array([10, 26, 42]))

In [26]:
#Seasons
Seasons = ["2013","2014","2015","2016","2017","2018","2019","2020","2021","2022"]
Sdict = {"2013":0,"2014":1,"2015":2,"2016":3,"2017":4,"2018":5,"2019":6,"2020":7,"2021":8,"2022":9}

#Players
Players = ["LionelMessi","ChristianoRonaldo","Neymar","LukaModric","RobertLewandowski","OlivierGiroud","KarimBenzema","KevinDeBruyne","MohamedSalah","Casemiro"]
Pdict = {"LionelMessi":0,"ChristianoRonaldo":1,"Neymar":2,"LukaModric":3,"RobertLewandowski":4,"OlivierGiroud":5,"KarimBenzema":6,"KevinDeBruyne":7,"MohamedSalah":8,"Casemiro":9}

#Salaries
LionelMessi_Salary = [15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,54000000]
ChristianoRonaldo_Salary = [12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
Neymar_Salary = [4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
LukaModric_Salary = [3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
RobertLewandowski_Salary = [4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
OlivierGiroud_Salary = [3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
KarimBenzema_Salary = [3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
KevinDeBruyne_Salary = [0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
MohamedSalah_Salary = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
Casemiro_Salary = [3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]
#Matrix
Salary = np.array([LionelMessi_Salary, ChristianoRonaldo_Salary, Neymar_Salary, LukaModric_Salary, RobertLewandowski_Salary, OlivierGiroud_Salary, KarimBenzema_Salary, KevinDeBruyne_Salary, MohamedSalah_Salary, Casemiro_Salary])

#Games 
LionelMessi_G = [80,77,82,82,73,82,58,78,61,35]
ChristianoRonaldo_G = [82,57,82,79,76,72,60,72,65,80]
Neymar_G = [79,78,75,81,76,79,62,76,77,69]
LukaModric_G = [80,65,77,66,69,77,55,67,77,40]
RobertLewandowski_G = [82,82,82,79,82,78,54,76,71,41]
OlivierGiroud_G = [70,69,67,77,70,77,57,74,79,44]
KarimBenzema_G = [78,64,80,78,45,80,60,70,62,82]
KevinDeBruyne_G = [35,35,80,74,82,78,66,81,81,27]
MohamedSalah_G = [40,40,40,81,78,81,39,0,10,51]
Casemiro_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([LionelMessi_G, ChristianoRonaldo_G, Neymar_G, LukaModric_G, RobertLewandowski_G, OlivierGiroud_G, KarimBenzema_G, KevinDeBruyne_G, MohamedSalah_G, Casemiro_G])

#Field Goals
LionelMessi_FG = [45,58,52,59,54,51,50,27,43,35]
ChristianoRonaldo_FG = [69,61,57,55,53,49,39,44,47,16]
Neymar_FG = [37,48,33,27,17,27,20,16,17,15]
LukaModric_FG = [0,0,0,1,3,1,4,3,4,2]
RobertLewandowski_FG = [48,52,58,56,51,61,41,47,46,50]
OlivierGiroud_FG = [19,13,7,15,10,14,13,15,10,16]
KarimBenzema_FG = [40,31,30,31,31,43,42,41,40,42]
KevinDeBruyne_FG = [6,6,17,11,14,11,13,11,19,17]
MohamedSalah_FG = [28,28,28,34,32,31,32,20,18,31]
Casemiro_FG = [6,2,9,4,9,2,6,9,5,2]
#Matrix
FieldGoals  = np.array([LionelMessi_FG, ChristianoRonaldo_FG, Neymar_FG, LukaModric_FG, RobertLewandowski_FG, OlivierGiroud_FG, KarimBenzema_FG, KevinDeBruyne_FG, MohamedSalah_FG, Casemiro_FG])

# Sum of columns (total for each season)
sum_columns_salary = np.sum(Salary, axis=0)
sum_columns_games = np.sum(Games, axis=0)
sum_columns_field_goals = np.sum(FieldGoals, axis=0)

print("Тоглогчдын цалингийн багануудын нийлбэр:")
print(sum_columns_salary)
print("Тоглогчдын нийт тоглолтын багануудын нийлбэр:")
print(sum_columns_games)
print("Тоглогчдын нийт гоолын багануудын нийлбэр:")
print(sum_columns_field_goals)


Тоглогчдын цалингийн багануудын нийлбэр:
[ 50299635  57248613  98406186 120776420 139835227 144667149 166489555
 189711742 205782921 235290923]
Тоглогчдын нийт тоглолтын багануудын нийлбэр:
[701 618 716 776 728 780 560 663 637 531]
Тоглогчдын нийт гоолын багануудын нийлбэр:
[298 299 291 293 274 290 260 233 249 226]


In [25]:
# Sum of rows (total for each player)
sum_rows_salary = np.sum(Salary, axis=1)
sum_rows_games = np.sum(Games, axis=1)
sum_rows_field_goals = np.sum(FieldGoals, axis=1)

print("Тоглогчдын цалингийн мөрнүүдийн нийлбэр:")
print(sum_rows_salary)
print("Тоглогчдын нийт тоглолтын мөрнүүдийн нийлбэр:")
print(sum_rows_games)
print("Тоглогчдын нийт гоолын мөрнүүдийн нийлбэр:")
print(sum_rows_field_goals)


Тоглогчдын цалингийн мөрнүүдийн нийлбэр:
[259806822 166205113 141461033 151622715 140546503 138008113 116051459
  88510296  75445211 130851106]
Тоглогчдын нийт тоглолтын мөрнүүдийн нийлбэр:
[708 725 752 673 727 684 699 639 460 643]
Тоглогчдын нийт гоолын мөрнүүдийн нийлбэр:
[474 490 257  18 510 132 371 125 282  54]
